pages:
  stage: deploy
  script:
      - wget https://github.com/rust-lang/mdBook/releases/download/v0.4.34/mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz
      - tar xvzf mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz
      - ./mdbook build
  artifacts:
      paths:
          - public
  only:
      - main 
  cache:
    - key:
        files:
          - mdbook
