[book]
authors = ["Randi Apriansyah"]
language = "en"
multilingual = false
src = "src"
title = "Test Driven Development With Go"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[build]
build-dir = "public"
